alias testQuery12='hdfs dfs -rm -f -r /user/cs4433/project3/output/;rm -f -r ~/shared_folder/output/output;spRun ./1-Queries/part1q1q2.py ; hdfs dfs -get /user/cs4433/project3/output/ ~/shared_folder/output/'
alias changeInput='hdfs dfs -rm -f -r /user/cs4433/project3/input/;hdfs dfs -put ~/shared_folder/input/ /user/cs4433/project3/input'
alias testQuery3='hdfs dfs -rm -f -r /user/cs4433/project3/output/;rm -f -r ~/shared_folder/output/output;spRun ./1-Queries/part1q3.py ; hdfs dfs -get /user/cs4433/project3/output/ ~/shared_folder/output/'
alias testPart1='hdfs dfs -rm -f -r /user/cs4433/project3/output/;rm -f -r ~/shared_folder/output/output;spRun ./1-Queries/part1q1q2.py; spRun ./1-Queries/part1q3.py ; hdfs dfs -get /user/cs4433/project3/output/ ~/shared_folder/output/'
alias runPart1='spRun ./1-Queries/part1q1q2.py; spRun ./1-Queries/part1q3.py ;'
alias spRun='~/spark/bin/spark-submit'
alias spCluster='~/spark/sbin/start-master.sh'
alias hdfs='~/hadoop/bin/hdfs'
alias hadoop='~/hadoop/sbin/start-all.sh'
alias startSparkAndHadoop='hadoop; spCluster;'

alias testPart2='hdfs dfs -rm -f -r /user/cs4433/project3/output/part2a/;rm -f -r ~/shared_folder/output/part2a;spRun ./2-sql/part2.py ; hdfs dfs -get /user/cs4433/project3/output/part2a/ ~/shared_folder/output/'
